name: CI workflow

# on:
#   push:
#     branches: ['main']
#   pull_request:
#     branches: ['main']
    
jobs: 
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt


      - name: test scripts
        run: |
          cd workingWithGivenData
          python readInDataFromFileAndPerformIntegration.py